#pragma once

#define OPENSYLAB_VERSION_MAJOR 0
#define OPENSYLAB_VERSION_MINOR 7
#define OPENSYLAB_VERSION_PATCH 0

#define OPENSYLAB_VERSION "0.7.0"
#define OPENSYLAB_VERSION_STRING "OpenSylab v0.7.0"
