#pragma once

#define OPENSYLAB_VERSION_MAJOR 0
#define OPENSYLAB_VERSION_MINOR 8
#define OPENSYLAB_VERSION_PATCH 0

#define OPENSYLAB_VERSION "0.8.0"
#define OPENSYLAB_VERSION_STRING "OpenSylab v0.8.0"
